/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import transformacoes.Objeto;
import java.awt.Color;
import java.awt.Polygon;
import javax.swing.JOptionPane;
import transformacoes.Transformacoes2D;

public class FormPrincipal extends javax.swing.JFrame {

    private Objeto fig;
    private Transformacoes2D tg;

    public FormPrincipal() {
        initComponents();
        configurarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRetangulo = new javax.swing.JButton();
        btnTriangulo = new javax.swing.JButton();
        tabTransformacoesGeometricas = new javax.swing.JTabbedPane();
        pnTranslacao = new javax.swing.JPanel();
        lblTx = new javax.swing.JLabel();
        txtTx = new javax.swing.JTextField();
        txtTy = new javax.swing.JTextField();
        lblTy = new javax.swing.JLabel();
        btnTranslacaoAplicar = new javax.swing.JButton();
        pnEscala = new javax.swing.JPanel();
        lblSx = new javax.swing.JLabel();
        txtSx = new javax.swing.JTextField();
        txtSy = new javax.swing.JTextField();
        lblSy = new javax.swing.JLabel();
        btnEscalaAplicar = new javax.swing.JButton();
        pnRotacao = new javax.swing.JPanel();
        txtAngulo = new javax.swing.JTextField();
        lblSx1 = new javax.swing.JLabel();
        btnRotacaoAplicar = new javax.swing.JButton();
        btnRotacaoAutomatica = new javax.swing.JButton();
        pn = new javax.swing.JPanel();
        lblPosicao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRetangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_retangulo.png"))); // NOI18N
        btnRetangulo.setText("retângulo");
        btnRetangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetangulo.setPreferredSize(new java.awt.Dimension(105, 100));
        btnRetangulo.setVerifyInputWhenFocusTarget(false);
        btnRetangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetanguloActionPerformed(evt);
            }
        });

        btnTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_triangulo.png"))); // NOI18N
        btnTriangulo.setText("triângulo");
        btnTriangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTriangulo.setPreferredSize(new java.awt.Dimension(105, 100));
        btnTriangulo.setVerifyInputWhenFocusTarget(false);
        btnTriangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrianguloActionPerformed(evt);
            }
        });

        lblTx.setText("Tx");

        txtTx.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtTy.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblTy.setText("Ty");

        btnTranslacaoAplicar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTranslacaoAplicar.setText("aplicar");
        btnTranslacaoAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranslacaoAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTranslacaoLayout = new javax.swing.GroupLayout(pnTranslacao);
        pnTranslacao.setLayout(pnTranslacaoLayout);
        pnTranslacaoLayout.setHorizontalGroup(
            pnTranslacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTranslacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTranslacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTx)
                    .addComponent(txtTx, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTranslacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTy)
                    .addComponent(txtTy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnTranslacaoAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnTranslacaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtTx, txtTy});

        pnTranslacaoLayout.setVerticalGroup(
            pnTranslacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTranslacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTranslacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnTranslacaoLayout.createSequentialGroup()
                        .addComponent(lblTy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnTranslacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTranslacaoAplicar)))
                    .addGroup(pnTranslacaoLayout.createSequentialGroup()
                        .addComponent(lblTx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabTransformacoesGeometricas.addTab("Translação", pnTranslacao);

        lblSx.setText("Sx");

        txtSx.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtSy.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblSy.setText("Sy");

        btnEscalaAplicar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEscalaAplicar.setText("aplicar");
        btnEscalaAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscalaAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnEscalaLayout = new javax.swing.GroupLayout(pnEscala);
        pnEscala.setLayout(pnEscalaLayout);
        pnEscalaLayout.setHorizontalGroup(
            pnEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEscalaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSx)
                    .addComponent(txtSx, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSy)
                    .addComponent(txtSy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnEscalaAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnEscalaLayout.setVerticalGroup(
            pnEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEscalaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnEscalaLayout.createSequentialGroup()
                        .addComponent(lblSy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEscalaAplicar)))
                    .addGroup(pnEscalaLayout.createSequentialGroup()
                        .addComponent(lblSx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabTransformacoesGeometricas.addTab("Escala", pnEscala);

        txtAngulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblSx1.setText("Ângulo");

        btnRotacaoAplicar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRotacaoAplicar.setText("aplicar");
        btnRotacaoAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotacaoAplicarActionPerformed(evt);
            }
        });

        btnRotacaoAutomatica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRotacaoAutomatica.setText("auto");
        btnRotacaoAutomatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotacaoAutomaticaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnRotacaoLayout = new javax.swing.GroupLayout(pnRotacao);
        pnRotacao.setLayout(pnRotacaoLayout);
        pnRotacaoLayout.setHorizontalGroup(
            pnRotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRotacaoLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(btnRotacaoAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRotacaoAutomatica, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnRotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnRotacaoLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(pnRotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSx1)
                        .addComponent(txtAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(213, Short.MAX_VALUE)))
        );
        pnRotacaoLayout.setVerticalGroup(
            pnRotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRotacaoLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnRotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRotacaoAutomatica, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnRotacaoAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnRotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnRotacaoLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(lblSx1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tabTransformacoesGeometricas.addTab("Rotação", pnRotacao);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabTransformacoesGeometricas))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabTransformacoesGeometricas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRetangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pn.setBackground(new java.awt.Color(255, 255, 255));
        pn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn.setPreferredSize(new java.awt.Dimension(600, 400));
        pn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnMouseMoved(evt);
            }
        });
        pn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMouseClicked(evt);
            }
        });

        lblPosicao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPosicao.setForeground(new java.awt.Color(153, 153, 153));
        lblPosicao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPosicao.setText("(X,Y)");

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLayout.createSequentialGroup()
                .addContainerGap(520, Short.MAX_VALUE)
                .addComponent(lblPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLayout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .addComponent(lblPosicao)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMouseMoved

        int x = evt.getX();
        int y = evt.getY();

        lblPosicao.setText(String.format("%03d,%03d", x, y));
    }//GEN-LAST:event_pnMouseMoved

    private void pnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMouseClicked
    }//GEN-LAST:event_pnMouseClicked

    private void btnRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetanguloActionPerformed
        fig.retangulo(Color.red);
    }//GEN-LAST:event_btnRetanguloActionPerformed

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        fig.triangulo(Color.red);
    }//GEN-LAST:event_btnTrianguloActionPerformed

    private void btnTranslacaoAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranslacaoAplicarActionPerformed
        try {
            double tx = Double.parseDouble(txtTx.getText());
            double ty = Double.parseDouble(txtTy.getText());

            tg.translacao(fig.getObjeto(), tx, ty);
            fig.desenhar(Color.red);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Os parâmetros informados são inválidos.", "Transf. Geométricas", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTranslacaoAplicarActionPerformed

    private void btnEscalaAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscalaAplicarActionPerformed
        try {
            double sx = Double.parseDouble(txtSx.getText());
            double sy = Double.parseDouble(txtSy.getText());
            tg.escala(fig.getObjeto(), sx, sy);
            fig.desenhar(Color.red);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Os parâmetros informados são inválidos.", "Transf. Geométricas", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEscalaAplicarActionPerformed

    private void btnRotacaoAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotacaoAplicarActionPerformed
        try {
            double angulo = Double.parseDouble(txtAngulo.getText());
            tg.rotacao(fig.getObjeto(), angulo);
            fig.desenhar(Color.red);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Os parâmetros informados são inválidos.", "Transf. Geométricas", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRotacaoAplicarActionPerformed

    private void btnRotacaoAutomaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotacaoAutomaticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRotacaoAutomaticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscalaAplicar;
    private javax.swing.JButton btnRetangulo;
    private javax.swing.JButton btnRotacaoAplicar;
    private javax.swing.JButton btnRotacaoAutomatica;
    private javax.swing.JButton btnTranslacaoAplicar;
    private javax.swing.JButton btnTriangulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPosicao;
    private javax.swing.JLabel lblSx;
    private javax.swing.JLabel lblSx1;
    private javax.swing.JLabel lblSy;
    private javax.swing.JLabel lblTx;
    private javax.swing.JLabel lblTy;
    private javax.swing.JPanel pn;
    private javax.swing.JPanel pnEscala;
    private javax.swing.JPanel pnRotacao;
    private javax.swing.JPanel pnTranslacao;
    private javax.swing.JTabbedPane tabTransformacoesGeometricas;
    private javax.swing.JTextField txtAngulo;
    private javax.swing.JTextField txtSx;
    private javax.swing.JTextField txtSy;
    private javax.swing.JTextField txtTx;
    private javax.swing.JTextField txtTy;
    // End of variables declaration//GEN-END:variables

    private void configurarFormulario() {
        this.setResizable(false);
        this.setTitle("Computação Gráfica");
        this.setLocationRelativeTo(null);

        fig = new Objeto(pn.getPreferredSize());
        pn.add(fig);
        fig.eixos(Color.GRAY);
        tg = new Transformacoes2D();
    }
}

