package view;

import java.awt.Color;
import java.awt.Polygon;

public class FormPrincipal extends javax.swing.JFrame {

    private Figura fig;
    private Polygon p;

    public FormPrincipal() {
        initComponents();
        configurarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRetangulo = new javax.swing.JButton();
        btnCirculo = new javax.swing.JButton();
        btnGradiente = new javax.swing.JButton();
        btnTriangulo2 = new javax.swing.JButton();
        pn = new javax.swing.JPanel();
        lblPosicao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRetangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_retangulo.png"))); // NOI18N
        btnRetangulo.setText("retângulo");
        btnRetangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetangulo.setPreferredSize(new java.awt.Dimension(105, 100));
        btnRetangulo.setVerifyInputWhenFocusTarget(false);
        btnRetangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetanguloActionPerformed(evt);
            }
        });

        btnCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_circulo.png"))); // NOI18N
        btnCirculo.setText("círculo");
        btnCirculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCirculo.setPreferredSize(new java.awt.Dimension(105, 100));
        btnCirculo.setVerifyInputWhenFocusTarget(false);
        btnCirculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });

        btnGradiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_gradiente.png"))); // NOI18N
        btnGradiente.setText("gradiente");
        btnGradiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGradiente.setPreferredSize(new java.awt.Dimension(105, 100));
        btnGradiente.setVerifyInputWhenFocusTarget(false);
        btnGradiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGradiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradienteActionPerformed(evt);
            }
        });

        btnTriangulo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_borracha.png"))); // NOI18N
        btnTriangulo2.setText("borracha");
        btnTriangulo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTriangulo2.setPreferredSize(new java.awt.Dimension(105, 100));
        btnTriangulo2.setVerifyInputWhenFocusTarget(false);
        btnTriangulo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTriangulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriangulo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGradiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnTriangulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTriangulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGradiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn.setBackground(new java.awt.Color(255, 255, 255));
        pn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn.setPreferredSize(new java.awt.Dimension(600, 400));
        pn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnMouseMoved(evt);
            }
        });
        pn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMouseClicked(evt);
            }
        });

        lblPosicao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPosicao.setForeground(new java.awt.Color(153, 153, 153));
        lblPosicao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPosicao.setText("(X,Y)");

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLayout.createSequentialGroup()
                .addContainerGap(520, Short.MAX_VALUE)
                .addComponent(lblPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLayout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .addComponent(lblPosicao)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMouseMoved

        int x = evt.getX();
        int y = evt.getY();

        lblPosicao.setText(String.format("%03d,%03d", x, y));
        
    }//GEN-LAST:event_pnMouseMoved

    private void pnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMouseClicked
        
        //Coordenada do Clique do usuário
        int x = evt.getX();
        int y = evt.getY();
        
        //Adicionar a coordenada ao Polígono.
        p.addPoint(x, y);
        fig.ponto(x, y, Color.RED);
        
        //Quando o usuário clicar 2x
        if (evt.getClickCount() == 2){
            fig.poligono(p, Color.BLUE);
        }
        
    }//GEN-LAST:event_pnMouseClicked

    private void btnRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetanguloActionPerformed
        int lagura = 400;
        int altura = 200;
        fig.retangulo(100, 100, lagura, altura, Color.red);
    }//GEN-LAST:event_btnRetanguloActionPerformed

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
        int raio = 200;
        fig.circulo(200, 100, raio, Color.red);
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void btnGradienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradienteActionPerformed

        Color ini = Color.RED;
        Color fim = Color.BLUE;
        
        //Coordenada inicial do Gradiente
        int xIni = 0;
        int yIni = 400;
        
        //Coordenada final do Gradiente
        int xFim = 600;
        int yFim = 0;
        
        fig.gradiente(ini, fim, xIni, yIni, xFim, yFim);
        
    }//GEN-LAST:event_btnGradienteActionPerformed

    private void btnTriangulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriangulo2ActionPerformed
        fig.limpar();
    }//GEN-LAST:event_btnTriangulo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnGradiente;
    private javax.swing.JButton btnRetangulo;
    private javax.swing.JButton btnTriangulo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPosicao;
    private javax.swing.JPanel pn;
    // End of variables declaration//GEN-END:variables

    private void configurarFormulario() {
        this.setResizable(false);
        this.setTitle("Computação Gráfica");
        this.setLocationRelativeTo(null);

        fig = new Figura(pn.getPreferredSize());
        pn.add(fig);
        fig.ponto(fig.getWidth() / 2, fig.getHeight() / 2, Color.blue);
        p = new Polygon();
    }
}
